export const langs = [
  ['Afrikaans', 'af-ZA'],
  ['አማርኛ', 'am-ET'],
  ['Azərbaycanca', 'az-AZ'],
  ['বাংলা বাংলাদেশ', 'bn-BD'],
  ['বাংলা ভারত', 'bn-IN'],
  ['Bahasa Indonesia', 'id-ID'],
  ['Bahasa Melayu', 'ms-MY'],
  ['Català', 'ca-ES'],
  ['Čeština', 'cs-CZ'],
  ['Dansk', 'da-DK'],
  ['Deutsch', 'de-DE'],
  ['English Australia', 'en-AU'],
  ['English Canada', 'en-CA'],
  ['English India', 'en-IN'],
  ['English Kenya', 'en-KE'],
  ['English Tanzania', 'en-TZ'],
  ['English Ghana', 'en-GH'],
  ['English New Zealand', 'en-NZ'],
  ['English Nigeria', 'en-NG'],
  ['English South Africa', 'en-ZA'],
  ['English Philippines', 'en-PH'],
  ['English United Kingdom', 'en-GB'],
  ['English United States', 'en-US'],
  ['Español Argentina', 'es-AR'],
  ['Español Bolivia', 'es-BO'],
  ['Español Chile', 'es-CL'],
  ['Español Colombia', 'es-CO'],
  ['Español Costa Rica', 'es-CR'],
  ['Español Ecuador', 'es-EC'],
  ['Español El Salvador', 'es-SV'],
  ['Español España', 'es-ES'],
  ['Español Estados Unidos', 'es-US'],
  ['Español Guatemala', 'es-GT'],
  ['Español Honduras', 'es-HN'],
  ['Español México', 'es-MX'],
  ['Español Nicaragua', 'es-NI'],
  ['Español Panamá', 'es-PA'],
  ['Español Paraguay', 'es-PY'],
  ['Español Perú', 'es-PE'],
  ['Español Puerto Rico', 'es-PR'],
  ['Español República Dominicana', 'es-DO'],
  ['Español Uruguay', 'es-UY'],
  ['Español Venezuela', 'es-VE'],
  ['Euskara', 'eu-ES'],
  ['Filipino', 'fil-PH'],
  ['Français', 'fr-FR'],
  ['Basa Jawa', 'jv-ID'],
  ['Galego', 'gl-ES'],
  ['ગુજરાતી', 'gu-IN'],
  ['Hrvatski', 'hr-HR'],
  ['IsiZulu', 'zu-ZA'],
  ['Íslenska', 'is-IS'],
  ['Italiano Italia', 'it-IT'],
  ['Italiano Svizzera', 'it-CH'],
  ['ಕನ್ನಡ', 'kn-IN'],
  ['ភាសាខ្មែរ', 'km-KH'],
  ['Latviešu', 'lv-LV'],
  ['Lietuvių', 'lt-LT'],
  ['മലയാളം', 'ml-IN'],
  ['मराठी', 'mr-IN'],
  ['Magyar', 'hu-HU'],
  ['ລາວ', 'lo-LA'],
  ['Nederlands', 'nl-NL'],
  ['नेपाली भाषा', 'ne-NP'],
  ['Norsk bokmål', 'nb-NO'],
  ['Polski', 'pl-PL'],
  ['Português Brasil', 'pt-BR'],
  ['Português Portugal', 'pt-PT'],
  ['Română', 'ro-RO'],
  ['සිංහල', 'si-LK'],
  ['Slovenščina', 'sl-SI'],
  ['Basa Sunda', 'su-ID'],
  ['Slovenčina', 'sk-SK'],
  ['Suomi', 'fi-FI'],
  ['Svenska', 'sv-SE'],
  ['Kiswahili Tanzania', 'sw-TZ'],
  ['Kiswahili Kenya', 'sw-KE'],
  ['ქართული', 'ka-GE'],
  ['Հայերեն', 'hy-AM'],
  ['தமிழ் இந்தியா', 'ta-IN'],
  ['தமிழ் சிங்கப்பூர்', 'ta-SG'],
  ['தமிழ் இலங்கை', 'ta-LK'],
  ['தமிழ் மலேசியா', 'ta-MY'],
  ['తెలుగు', 'te-IN'],
  ['Tiếng Việt', 'vi-VN'],
  ['Türkçe', 'tr-TR'],
  ['اُردُو پاکستان', 'ur-PK'],
  ['اُردُو بھارت', 'ur-IN'],
  ['Ελληνικά', 'el-GR'],
  ['български', 'bg-BG'],
  ['Pусский', 'ru-RU'],
  ['Српски', 'sr-RS'],
  ['Українська', 'uk-UA'],
  ['한국어', 'ko-KR'],
  ['中文 普通话 (中国大陆)', 'cmn-Hans-CN'],
  ['中文 普通话 (香港)', 'cmn-Hans-HK'],
  ['中文 中文 (台灣)', 'cmn-Hant-TW'],
  ['中文 粵語 (香港)', 'yue-Hant-HK'],
  ['日本語', 'ja-JP'],
  ['हिन्दी', 'hi-IN'],
  ['ภาษาไทย', 'th-TH'],
];
